# Generated by Django 3.0.3 on 2020-08-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_aadharcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('complain_id', models.AutoField(primary_key=True, serialize=False)),
                ('complainer', models.CharField(max_length=64)),
                ('victim', models.CharField(max_length=64)),
                ('abuser', models.CharField(max_length=64)),
                ('tweet', models.TextField(blank=True, null=True)),
                ('completed', models.CharField(max_length=64)),
                ('time_now', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
