# Generated by Django 3.0.3 on 2020-08-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('complain_id', models.AutoField(primary_key=True, serialize=False)),
                ('platform_id', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=128)),
                ('platform', models.CharField(max_length=64)),
                ('result', models.CharField(max_length=64)),
                ('time_now', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('complain_id', models.AutoField(primary_key=True, serialize=False)),
                ('platform_id', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=128)),
                ('platform', models.CharField(max_length=64)),
                ('result', models.CharField(max_length=64)),
                ('time_now', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('complain_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=128)),
                ('result', models.CharField(max_length=64)),
                ('time_now', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
